name: Hello World
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "This is Build Step"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: echo "This is Testing Phase"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Step
        run: echo "This is Deployment Stage"

